---
version: 2

jobs:
  test:
    # Whenever the Go version is updated here, .travis.yml should also be
    # updated.
    docker:
    - image: circleci/golang:1.10
    working_directory: /go/src/github.com/terrycain/389ds_exporter
    resource_class: large

    steps:
    - checkout
    - run: make promu
    - run: make
    - run: rm -v 389ds_exporter

  build:
    machine: true
    working_directory: /home/circleci/.go_workspace/src/github.com/terrycain/389ds_exporter

    steps:
    - checkout
    - run: make promu
    - run: promu crossbuild -v
    - persist_to_workspace:
        root: .
        paths:
        - .build

  docker_hub_master:
    docker:
    - image: circleci/golang:1.10
    working_directory: /go/src/github.com/terrycain/389ds_exporter

    steps:
    - checkout
    - setup_remote_docker
    - attach_workspace:
        at: .
    - run: ln -s .build/linux-amd64/389ds_exporter 389ds_exporter
    - run: make docker
    - run: docker images
    - run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
    - run: make docker-publish

  docker_hub_release_tags:
    docker:
    - image: circleci/golang:1.10
    working_directory: /go/src/github.com/terrycain/389ds_exporter

    steps:
    - checkout
    - setup_remote_docker
    - run: mkdir -v -p ${HOME}/bin
    - run: curl -L 'https://github.com/aktau/github-release/releases/download/v0.7.2/linux-amd64-github-release.tar.bz2' | tar xvjf - --strip-components 3 -C ${HOME}/bin
    - run: echo 'export PATH=${HOME}/bin:${PATH}' >> ${BASH_ENV}
    - attach_workspace:
        at: .
    - run: make promu
    - run: promu crossbuild tarballs
    - run: promu checksum .tarballs
    - run: promu release .tarballs
    - store_artifacts:
        path: .tarballs
        destination: releases
    - run: ln -s .build/linux-amd64/terrycain 389ds_exporter
    - run: make docker DOCKER_IMAGE_TAG=$CIRCLE_TAG
    - run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
    - run: |
        if [[ "$CIRCLE_TAG" =~ ^v[0-9]+(\.[0-9]+){2}$ ]]; then
          make docker-tag-latest DOCKER_IMAGE_TAG="$CIRCLE_TAG"
        fi
    - run: make docker-publish

workflows:
  version: 2
  prometheus:
    jobs:
    - test:
        filters:
          tags:
            only: /.*/
    - build:
        filters:
          tags:
            only: /.*/
    - docker_hub_master:
        requires:
        - test
        - build
        filters:
          branches:
            only: master
    - docker_hub_release_tags:
        requires:
        - test
        - build
        filters:
          tags:
            only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
          branches:
            ignore: /.*/
