name: Build & deploy release

on:
  push:
    tags:
    - v*
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Build project
      run: |
        go build \
          -ldflags "-X github.com/prometheus/common/version.Version=${GITHUB_REF#refs/*/} -X github.com/prometheus/common/version.Branch=master -X github.com/prometheus/common/version.Revision=${{github.sha}} -X github.com/prometheus/common/version.BuildUser=github-action -X github.com/prometheus/common/version.BuildDate=$(date +'%Y%m%d-%H:%M:%S')" \
          -o 389ds_exporter -v .
    - name: Release binary
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          389ds_exporter
          LICENSE
          README.md
